# Generated by Django 5.1.4 on 2025-06-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='caregory',
            new_name='catagory',
        ),
    ]
